all:
	g++ main.cpp Queue.h Classify.cpp stdafx.cpp -I/usr/local/include/gti/ -std=c++11 -lpthread -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_videoio  -lGTILibrary-static -lftd3xx -o test
